### ISSUE TITLE
Error ketika getSettlement

### ISSUE THREAD

**Issue by kingrootid** [apriady/nodejs-bca-scraper#8]
```bash
error  Cannot read properties of null (reading '1')
```

```js
const bca = require("nodejs-bca-scraper");
bca
  .getSettlement("XX", "XXX")
  .then(res => {
    console.log("settlement ", res);
  })
  .catch(err => {
    console.log("error ", err);
  });
```

**Comment by rizkiandrianto** [comment]
Fixed on PR #10

**Comment by simaung** [comment]
`error Cannot read properties of null (reading '1')`

still get this error
